title: "Hello hsun-code"
author: "Hao SUN"
# description: "Some short description of your blog can go here." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.

email: "hsun-code@outlook.com"
github_username: "hsun-code"

theme: "minima"

exclude: files
